@ADMIN_TOKEN = YWRtaW46YWRtaW5hZG1pbg==
@KEVIN_TOKEN = a2V2aW46dXNlcnVzZXI=
@ALICE_TOKEN = YWxpY2U6dXNlcnVzZXI=

# Cookie: oam.Flash.RENDERMAP.TOKEN=-14ga8bj3vz; LtpaToken2=tdhGxG3ePXEe3i7AE/zGhmshHfpqDsdPZ7mm5q+33+ceKqGZ2rqVezzMR+b2zz1djyf217m8DySLpx+oczY5b9UGVLMC4/Y9px2tmBA8VZ5lRLJ/0yinZetKPbVJKGfnCuDVPKw/cliaus0SgE05fJCB6rKSe0xFFbNClD+RZspbE3PZHj/NGsIFNMKZlN1lC6P2v+hCOznFjNCt2+uBoIWhheSxZmyt6LIeejEUoY1kEExlc7X75q2/iso1PVpqv2gisEOVRGD3d0MCDx75GT36P7ri9OiWa7zdB8HxBF2XPuVJ2rVFxR/SklH/d3fvmVzv06E51mYZEUn4rJROezZDtDPuR0uQwA3MJhdskFxdc9AmnFOr5vyyBw3vrnVCkKpavcF7x0WOvE5nHhddFer539cXtjktEOTuVFkUuy80qPuUtvdPlkG/lr8hNTi8HLmKy0ZyLD2ixdAc+jvam3YJkY5jWCacTZP/rO+MANTxT3gEOzK4jvTsSRHb4kT5Q1OZvWRFum8WWeCGsLJ4hQ==; JSESSIONID=0000tKi42H9W_w1iAkRYrMuH1CQ:e8a3ca98-57e5-4883-8880-c466f0b9a340; ajs_anonymous_id=16ab1d2b-88f9-4c20-bcde-585aedf1a145

# Get all users. Everyone should be able to that.
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/users

### Create user - anyone
// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/users/123e4567-e89b-12d3-bc56-426614174123
Content-Type: application/json

{
  "login": "test2",
  "name": "John22",
  "surname": "Doe",
  "email": "john@exampl2e.com",
  "password": "password123",
  "gender": "MALE"
}

### Get all games - everyone should be able to that.
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/games
Cookie: oam.Flash.RENDERMAP.TOKEN=-9e84b2x9n; LtpaToken2=8guyac5SzJwG95L8Uv7mtZrwf2pOiStqgoSVEky0w2GJYve9juEynzZTAAikBlF+z6V5GSQDfppXl4HSI+Nqv/vALjm2jLvZNpFLiqYn+t3sybbhYcS303cyjjQ/JSjO/irbVT8CGBg4B4oPFHAHr/7Wj/St2NyQxkuWLUM7D5rmuP/4n0kxDRkNR0PD5MBXkb2f2E+XdLZGuZ48H0j/8sU2ivcwAERWY5Hx++glEOjOw8auHM2XKH1EW9ma/PWCv3V9vs/iwkJVu5a7Kx1IxzfR1OOLCfRopPor8henIuXWFCsPWJuKnbvebWm3g/m4HDr7NYSoepfIfMt87a2/7Z2okqjHrpetJDcM+MIaMObDWUEaoGrlRcMAuawaKOt5to+k1pbgtd6GzohywW4WlTPL0ee3HSgtO2+wHx8x0oH6IcHGua+MKZQuLbMe9nU1g3BYwN8l8UrKeEaVOrITOp1MAyGIPnYB3F+nSne+tvSXiJesMvrDt+Ov5m/3EFC42Oi5ImQriV3faG717WGenA==; WASReqURL=http://:9080/simple-rpg/game/games_list.xhtml; JSESSIONID=0000J3IXL6WMEwK_nBFK7rR78UZ:49ffd73a-1f57-41f8-aeff-36399ef0fd87; ajs_anonymous_id=16ab1d2b-88f9-4c20-bcde-585aedf1a145


### Get specific game - everyone should be able to that.
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4197
Authorization: Basic {{KEVIN_TOKEN}}


### Create a new game - only admin should do that.
// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196
Content-Type: application/json
Authorization: Basic {{ADMIN_TOKEN}}

{
  "name": "My New RPG",
  "dateOfRelease": "2025-10-29",
  "type": "RPG"
}


### Delete new game - only admin should do that.
// @no-cookie-jar
DELETE  http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196
Authorization: Basic {{ADMIN_TOKEN}}

### Create a new game - should fail.
// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196
Content-Type: application/json
Authorization: Basic {{KEVIN_TOKEN}}

{
  "name": "My New RPG",
  "dateOfRelease": "2025-10-29",
  "type": "RPG"
}

### Delete new game - should fail.
// @no-cookie-jar
DELETE  http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196
Authorization: Basic {{KEVIN_TOKEN}}

### Get all reviews for a game - admin should be able to do that.
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews
Authorization: Basic {{ADMIN_TOKEN}}

### Get all reviews for a game - user should see just his
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews
Authorization: Basic {{KEVIN_TOKEN}}

### Get all reviews for a game - user should see just his
// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews
Authorization: Basic {{ALICE_TOKEN}}

### Create a new review - should be assigned to Kevin
// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Content-Type: application/json
Authorization: Basic {{KEVIN_TOKEN}}

{
  "description": "Awesome game, loved it!",
  "mark": 9.5,
  "userId": "ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197"
}

### Delete review - admin can do it all.
// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Authorization:  Basic {{ADMIN_TOKEN}}

### Update review - admin can do it all
// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Content-Type: application/json
Authorization:  Basic {{ADMIN_TOKEN}}

{
  "description": "Actually, I chawwnged my mind, it's amazing!"
}

### Delete review - user should be able to change his. Should fail.
// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Authorization:  Basic {{ALICE_TOKEN}}


### Delete review - user should be able to change his.
// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Authorization:  Basic {{KEVIN_TOKEN}}

### Update review - user should be able to change his.
// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Content-Type: application/json
Authorization:  Basic {{ADMIN_TOKEN}}

{
  "description": "Actually, I changed my mind, it's amazing!"
}

### Update review - user should be able to change his. Should fail.
// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/games/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4196/reviews/ed6cfb2a-cad7-47dd-9b56-9d1e3c7b4111
Content-Type: application/json
Authorization:  Basic {{ALICE_TOKEN}}

{
  "description": "Actually, I changed my mind, it's amazing!"
}
